name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - main

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#     - name: Install dependencies
#       run: npm install
#     - name: Build Docker image
#       run: docker build -t node .
#     - name: Login to Docker Hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#     - name: Push Docker image to Docker Hub
#       run: docker tag node ${{ secrets.DOCKER_USERNAME }}/node:latest && docker push ${{ secrets.DOCKER_USERNAME }}/node:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        password: ${{ secrets.EC2_PASS }}
        port: 22
        script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            sudo docker pull siddarthpaladi/node
            sudo docker stop node || true
            sudo docker rm node || true
            sudo docker run -d -p 3333:3333 --name my-app siddarthpaladi/node:latest

