name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: /tmp/id_rsa
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/node:latest
          docker stop node || true
          docker rm node || true
          docker run -d -p 3333:3333 --name my-app ${{ secrets.DOCKER_USERNAME }}/node:latest
        timeout: 30s
        command_timeout: 10m
        debug: false
