name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Checks out your repository code

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/node:latest

          # Stop and remove any existing container named 'node'
          docker stop node || true
          docker rm node || true

          # Run the new Docker container
          docker run -d -p 3333:3333 --name node ${{ secrets.DOCKER_USERNAME }}/node:latest
